name: Trigger Personal Repo

on:
  push:
    branches:
      - master

jobs:
  send-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Nixos configuration repo to update website
        run: |
          curl -X POST https://api.github.com/repos/pietdevries94/personal-nix-channel/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PERSONAL_TOKEN }} \
          --data '{"event_type": "update"}'